version: '3.8'
services:
  attend-db:
    container_name: attend-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'attend-db'
      MYSQL_ROOT_PASSWORD: 'DevPassword1!'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
