name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  SERVICE_NAME: attend-client
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/attend-client
  REGION: europe-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          version: '290.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SERVICE_ACC_KEY }}
          export_default_credentials: true

      - name: Build and Push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated
